name: Python Hello World with Input Variable

on:
  push:
     branches:
       - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your Name'
        required: true
        default: 'World'

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Run Python Program with Input Variable
        env:
          INPUT_NAME: ${{ inputs.name }}  # Pass input to env variable
        run: python hello.py
