name: Python Hello World with Input Variable and Auto Branch

on:
  push:
     branches:
       - main
  workflow_dispatch:
    inputs:
      name:
        description: 'Enter your Name'
        required: true
        default: 'World'

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create a new branch
        run: |
          BRANCH_NAME=new-branch-$(date +%Y%m%d%H%M%S)
          echo "Branch Name: $BRANCH_NAME"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

      - name: Run Python Program with Input Variable
        env:
          INPUT_NAME: ${{ inputs.name }}
        run: python hello.py
